import { expect, test } from '@playwright/test'
import { createServer } from 'vite'
import { join } from 'path'
import { mkdirSync } from 'fs'
import { launchApp } from './helpers'

test('標準Componentは状態・Surface・Reducedを表示し、キーボードで操作できる', async () => {
  const server = await createServer({ root: join(process.cwd(), 'src/renderer'), configFile: false, server: { host: '127.0.0.1', port: 0 } })
  await server.listen()
  const address = server.httpServer?.address()
  if (!address || typeof address === 'string') throw new Error('Component Gallery server did not start')
  const ctx = await launchApp()
  try {
    const windowPromise = ctx.app.waitForEvent('window')
    await ctx.app.evaluate(async ({ BrowserWindow }, url) => {
      const window = new BrowserWindow({ show: false, webPreferences: { sandbox: true, contextIsolation: true } })
      await window.loadURL(url)
    }, `http://127.0.0.1:${address.port}/component-gallery.html`)
    const page = await windowPromise
    const errors: string[] = []
    page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
    page.on('pageerror', (error) => errors.push(String(error)))
    await expect(page.getByRole('heading', { name: '標準Componentの見本帳' })).toBeVisible()
    const normal = page.getByLabel('通常の動き')
    const reduced = page.getByLabel('動きを抑える')
    const disclosure = normal.getByRole('button', { name: /詳細を表示/ })
    await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
    await disclosure.focus()
    expect(await disclosure.evaluate((el) => getComputedStyle(el).outlineStyle)).toBe('solid')
    await page.keyboard.press('Enter')
    await expect(disclosure).toHaveAttribute('aria-expanded', 'true')
    await expect(normal.getByRole('button', { name: '補足操作' })).toBeVisible()
    await page.keyboard.press('Space')
    await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
    expect(await normal.getByText('開いている間、内容へTabで移動できます。').evaluate((el) => el.closest('[role="region"]')?.inert)).toBe(true)
    await expect(normal.getByRole('button', { name: '利用できない項目' })).toBeDisabled()
    await page.getByRole('button', { name: '切替（Toggle） toggle' }).click()
    const toggle = normal.getByRole('switch', { name: '通知を受け取る' })
    await toggle.focus()
    await page.keyboard.press('Space')
    await expect(toggle).toHaveAttribute('aria-checked', 'true')
    await expect(toggle.locator('.ak-ui-toggle__state')).toHaveText('オン')
    await expect(normal.getByRole('switch', { name: '管理者が設定' })).toBeDisabled()
    expect(await reduced.getByRole('switch', { name: '管理者が設定' }).locator('.ak-motion-toggle-thumb').evaluate((el) => getComputedStyle(el).transform)).toBe('none')
    await page.getByRole('button', { name: 'パネル（Panel） panel' }).click()
    expect(await normal.locator('[data-surface="standard"]').evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-subtle-in')
    expect(await normal.locator('[data-surface="media-safe"]').evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    expect(await normal.locator('[data-surface="opaque-media"]').evaluate((el) => getComputedStyle(el).animationName)).toBe('none')
    expect(await reduced.locator('[data-surface="standard"]').evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    await page.getByRole('button', { name: '登場を再生' }).click()
    await page.getByRole('button', { name: 'カード（Card） card' }).click()
    expect(await normal.locator('.ak-ui-card:not(button)').count()).toBe(1)
    expect(await normal.locator('[data-surface="media-safe"].ak-ui-card').evaluate((el) => getComputedStyle(el).transform)).toBe('none')
    await expect(normal.getByRole('button', { name: /Disabled/ })).toBeDisabled()
    await page.keyboard.press('Tab')
    await normal.getByRole('button', { name: /Interactive \/ Standard/ }).focus()
    expect(await normal.getByRole('button', { name: /Interactive \/ Standard/ }).evaluate((el) => getComputedStyle(el).outlineStyle)).toBe('solid')
    await page.keyboard.press('Enter')
    await expect(normal.getByText('選択しました')).toBeVisible()
    await page.getByRole('button', { name: 'ボタン（Button） button' }).click()
    const save = normal.getByRole('button', { name: '保存', exact: true })
    await save.focus()
    await page.keyboard.press('Shift+Tab')
    await page.keyboard.press('Tab')
    await expect(save).toBeFocused()
    expect(await save.evaluate((el) => getComputedStyle(el).outlineStyle)).toBe('solid')
    await page.keyboard.press('Enter')
    await page.keyboard.press('Space')
    await expect(normal.getByText('保存操作: 2回')).toBeVisible()
    expect(await save.evaluate((el) => getComputedStyle(el).transitionDuration)).toContain('0.12s')
    expect(await reduced.getByRole('button', { name: '保存', exact: true }).evaluate((el) => getComputedStyle(el).transitionDuration)).toContain('0.001s')
    await expect(normal.getByRole('button', { name: '保存できません' })).toBeDisabled()
    const close = normal.getByRole('button', { name: '閉じる', exact: true })
    await expect(close).toHaveAttribute('aria-label', '閉じる')
    await close.focus()
    await page.keyboard.press('Enter')
    await expect(normal.getByRole('button', { name: '閉じる（無効）' })).toBeDisabled()
    mkdirSync(join('test-results', 'screenshots'), { recursive: true })
    await page.setViewportSize({ width: 1100, height: 850 })
    await page.screenshot({ path: join('test-results', 'screenshots', 'component-gallery-button.png') })
    await page.setViewportSize({ width: 640, height: 780 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: join('test-results', 'screenshots', 'component-gallery-button-narrow.png'), fullPage: true })
    await page.getByRole('button', { name: 'テキスト入力（TextField） text-field' }).click()
    const field = normal.getByRole('textbox', { name: '標準の入力' })
    await field.focus()
    await page.keyboard.press('Shift+Tab')
    await page.keyboard.press('Tab')
    await expect(field).toBeFocused()
    expect(await field.evaluate((el) => getComputedStyle(el).outlineStyle)).toBe('solid')
    await field.fill('入力済み')
    await expect(field).toHaveValue('入力済み')
    const required = normal.getByRole('textbox', { name: /保存先/ })
    await expect(required).toHaveAttribute('required', '')
    await expect(required).toHaveAttribute('placeholder', 'フォルダー名を入力')
    const requiredDescription = await required.getAttribute('aria-describedby')
    expect(requiredDescription).toBeTruthy()
    await expect(page.locator(`[id="${requiredDescription}"]`)).toHaveText('生成したファイルの保存先です')
    const readonly = normal.getByRole('textbox', { name: '変更できない値' })
    await expect(readonly).toHaveAttribute('readonly', '')
    await expect(readonly).toHaveValue('既存の値')
    await expect(normal.getByRole('textbox', { name: '利用できない項目' })).toBeDisabled()
    const invalid = normal.getByRole('textbox', { name: '検証エラー' })
    await expect(invalid).toHaveAttribute('aria-invalid', 'true')
    const invalidDescriptions = (await invalid.getAttribute('aria-describedby'))?.split(' ') ?? []
    expect(invalidDescriptions).toHaveLength(2)
    await expect(page.locator(`[id="${invalidDescriptions[0]}"]`)).toHaveText('入力値を確認してください')
    await expect(page.locator(`[id="${invalidDescriptions[1]}"]`)).toHaveText('フォルダーが見つかりません')
    await page.setViewportSize({ width: 1100, height: 850 })
    await page.screenshot({ path: join('test-results', 'screenshots', 'component-gallery-text-field.png'), fullPage: true })
    await page.setViewportSize({ width: 640, height: 780 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: join('test-results', 'screenshots', 'component-gallery-text-field-narrow.png'), fullPage: true })
    await page.getByRole('button', { name: '空状態（EmptyState） empty-state' }).click()
    const emptyStatus = normal.getByRole('status')
    await expect(emptyStatus).toContainText('まだ項目がありません')
    await expect(reduced.getByRole('status')).toContainText('上の操作から追加できます。')
    await normal.getByRole('button', { name: '項目を表示' }).click()
    await expect(emptyStatus).toHaveCount(0)
    await expect(normal.getByText('保存済みの項目')).toBeVisible()
    await normal.getByRole('button', { name: '空に戻す' }).click()
    await expect(emptyStatus).toBeVisible()
    await page.setViewportSize({ width: 1100, height: 850 })
    await page.screenshot({ path: join('test-results', 'screenshots', 'component-gallery-empty-state.png'), fullPage: true })
    await page.setViewportSize({ width: 640, height: 780 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: join('test-results', 'screenshots', 'component-gallery-empty-state-narrow.png'), fullPage: true })
    expect(ctx.consoleErrors).toEqual([])
    expect(errors).toEqual([])
  } finally {
    await ctx.close()
    await server.close()
  }
})
