import { expect, test } from '@playwright/test'
import { createServer } from 'vite'
import { join } from 'path'
import { mkdirSync } from 'fs'
import { launchApp } from './helpers'

test('Galleryは通常/Reduced比較、Replay、初回画像契約を確認できる', async () => {
  const server = await createServer({ root: join(process.cwd(), 'src/renderer'), configFile: false, server: { host: '127.0.0.1', port: 0 } })
  await server.listen()
  const address = server.httpServer?.address()
  if (!address || typeof address === 'string') throw new Error('Gallery server did not start')
  const ctx = await launchApp()
  try {
    const windowPromise = ctx.app.waitForEvent('window')
    await ctx.app.evaluate(async ({ BrowserWindow }, url) => {
      const window = new BrowserWindow({ show: false, webPreferences: { sandbox: true, contextIsolation: true } })
      await window.loadURL(url)
    }, `http://127.0.0.1:${address.port}/gallery.html`)
    const page = await windowPromise
    const galleryErrors: string[] = []
    page.on('console', (message) => { if (message.type() === 'error') galleryErrors.push(message.text()) })
    page.on('pageerror', (error) => galleryErrors.push(String(error)))
    await expect(page.getByRole('heading', { name: '動きの見本帳' })).toBeVisible()
    await expect(page.getByTestId('preview-normal')).toBeVisible()
    await expect(page.getByTestId('preview-reduced')).toBeVisible()
    mkdirSync(join('test-results', 'screenshots'), { recursive: true })
    await page.setViewportSize({ width: 1100, height: 850 })
    await page.screenshot({ path: join('test-results', 'screenshots', 'motion-gallery.png') })
    await page.setViewportSize({ width: 640, height: 780 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: join('test-results', 'screenshots', 'motion-gallery-narrow.png') })
    await page.setViewportSize({ width: 1100, height: 850 })
    await page.getByRole('button', { name: '控えめな通知・登場 ToastEnterCompact' }).click()
    await expect(page.getByText('template src/renderer/src/ui/chrome.css toast-in')).toBeVisible()
    await page.getByRole('button', { name: '通知の強調・登場 ToastRiseIn' }).click()
    await expect(page.getByText('VideoDeck renderer/styles/main.css toastIn')).toBeVisible()
    await expect(page.getByLabel('Toast比較').locator('.mg-toast-variant-grid > div')).toHaveCount(3)
    const normal = page.getByTestId('preview-normal').locator('.ak-motion-toast-rise-in')
    const reduced = page.getByTestId('preview-reduced').locator('.ak-motion-toast-rise-in')
    expect(await normal.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-toast-rise-in')
    expect(await reduced.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    await page.emulateMedia({ reducedMotion: 'reduce' })
    expect(await normal.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-toast-rise-in')
    expect(await reduced.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    await page.getByRole('button', { name: '両方再生' }).click()
    await expect(page.getByTestId('preview-normal').locator('.ak-motion-toast-rise-in')).toBeVisible()
    await page.getByRole('button', { name: '画像の初回表示 ImageFirstPaintFade' }).click()
    const image = page.getByTestId('preview-normal').getByRole('img', { name: '初回表示のサンプル' })
    await expect(image).toBeVisible()
    await page.waitForTimeout(350)
    await page.getByTestId('preview-normal').getByRole('button', { name: /再描画/ }).click()
    await expect(image).not.toHaveClass(/is-animating/)
    await page.getByRole('button', { name: '画像入りパネル・フェード PanelFadeInMediaSafe' }).click()
    await expect(page.getByRole('heading', { name: '画像入りパネル・フェード' })).toBeVisible()
    await page.getByRole('button', { name: 'PanelFadeInMediaSafeをコピー' }).click()
    await expect(page.getByText('コピーしました')).toBeVisible()
    const panelNormal = page.getByTestId('preview-normal').locator('.ak-motion-panel-media-safe')
    const panelReduced = page.getByTestId('preview-reduced').locator('.ak-motion-panel-media-safe')
    expect(await panelNormal.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    expect(await panelReduced.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    await page.getByRole('button', { name: '小型メニュー・登場 MenuPopIn' }).click()
    const menuNormal = page.getByTestId('preview-normal').getByRole('menu')
    const menuReduced = page.getByTestId('preview-reduced').getByRole('menu')
    expect(await menuNormal.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-menu-pop-in')
    expect(await menuReduced.evaluate((el) => getComputedStyle(el).animationName)).toBe('ak-motion-fade-in')
    await page.getByRole('button', { name: '小型メニュー・退場 MenuPopOut' }).click()
    await page.getByTestId('preview-normal').scrollIntoViewIfNeeded()
    await page.screenshot({ path: join('test-results', 'screenshots', 'motion-gallery-menu.png') })
    await page.getByTestId('preview-normal').getByRole('button', { name: 'メニューを閉じる' }).click()
    await page.getByTestId('preview-reduced').getByRole('button', { name: 'メニューを閉じる' }).click()
    await expect(page.getByTestId('preview-normal').getByRole('menu')).toHaveCount(0)
    await expect(page.getByTestId('preview-reduced').getByRole('menu')).toHaveCount(0)
    await expect(page.getByTestId('preview-reduced').getByText('閉じました')).toBeVisible()
    await page.getByTestId('preview-normal').getByRole('button', { name: 'メニューを開く' }).click()
    await expect(page.getByTestId('preview-normal').getByRole('menu')).toBeVisible()
    await page.addStyleTag({ content: '.mg-stage .ak-motion-menu-pop-out { animation: none !important; }' })
    await page.getByTestId('preview-normal').getByRole('button', { name: 'メニューを閉じる' }).click()
    await expect(page.getByTestId('preview-normal').getByRole('menu')).toHaveCount(0)
    expect(ctx.consoleErrors).toEqual([])
    expect(galleryErrors).toEqual([])
  } finally {
    await ctx.close()
    await server.close()
  }
})
